### ISSUE TITLE
Test fails nondeterministically.

### ISSUE THREAD

**Issue by guimard** [d3/d3-timer#37]
Hello,
a simple`npm install; npm run test` fails now:
```
# timer(callback, delay) first invokes the callback after the specified delay
not ok 47 should be in range
  ---
    operator: inRange
    expected: [ 140, 160 ]
    actual:   166
    at: Test.tape.Test.inRange (/home/xavier/dev/debian/src/pkg-js/packages/node-d3-timer/test/inRange.js:4:8)
    stack: |-
      Error: should be in range
          at Test.assert [as _assert] (/home/xavier/dev/debian/src/pkg-js/packages/node-d3-timer/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/xavier/dev/debian/src/pkg-js/packages/node-d3-timer/node_modules/tape/lib/test.js:76:32)
          at Test.tape.Test.inRange (/home/xavier/dev/debian/src/pkg-js/packages/node-d3-timer/test/inRange.js:4:8)
          at Test.bound [as inRange] (/home/xavier/dev/debian/src/pkg-js/packages/node-d3-timer/node_modules/tape/lib/test.js:76:32)
          at /home/xavier/dev/debian/src/pkg-js/packages/node-d3-timer/test/timer-test.js:69:10
          at timerFlush (/home/xavier/dev/debian/src/pkg-js/packages/node-d3-timer/build/d3-timer.js:68:48)
          at Timeout.wake [as _onTimeout] (/home/xavier/dev/debian/src/pkg-js/packages/node-d3-timer/build/d3-timer.js:78:5)
          at ontimeout (timers.js:436:11)
          at tryOnTimeout (timers.js:300:5)
          at listOnTimeout (timers.js:263:5)
  ...
# timer(callback, delay) computes the elapsed time relative to the delay
ok 48 should be in range
```

**Comment by mbostock** [comment]
The test is slightly nondeterministic, unfortunately. I should probably increase the allowed range.

**Comment by mbostock** [comment]
I don’t know how to fix this but I would welcome ideas.
